// GENERATED by MangaPrompts tgbot/tools/bench/export_catalog.py from the
// bench verdicts (MangaPrompts/docs/hair-matrix.md). Do not edit by hand.

import 'hair_mask.dart';
import 'hairstyle_preset.dart';

const kHairstyles = <HairstylePreset>[
];

const kHairColours = <HairColourPreset>[
];
