// GENERATED by MangaPrompts tgbot/tools/bench/export_catalog.py from the
// bench verdicts (MangaPrompts/docs/hair-matrix.md). Do not edit by hand.

import 'hair_mask.dart';
import 'hairstyle_preset.dart';

const kHairstyles = <HairstylePreset>[
  HairstylePreset(
    id: 'curtain-bangs',
    label: 'Záclonová ofina',
    group: kHairGroupWomen,
    section: 'Ofiny',
    block:
        'curtain bangs, soft face-framing fringe parted in the middle and swept to both sides, blending into the lengths',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.curtain, updo: false),
  ),
  HairstylePreset(
    id: 'lob',
    label: 'Dlouhé mikádo',
    group: kHairGroupWomen,
    section: 'Střihy',
    block:
        'long bob haircut (lob), one-length hair ending at the collarbone, sleek and slightly longer in front',
    shape: HairShape(length: HairLength.medium, bangs: HairBangs.none, updo: false),
  ),
  HairstylePreset(
    id: 'french-bob',
    label: 'Krátké francouzské mikádo',
    group: kHairGroupWomen,
    section: 'Střihy',
    block:
        'french bob, short chin-length bob with a full straight fringe, effortless parisian look',
    shape: HairShape(length: HairLength.medium, bangs: HairBangs.full, updo: false),
  ),
  HairstylePreset(
    id: 'face-framing',
    label: 'Vrstvy rámující obličej',
    group: kHairGroupWomen,
    section: 'Střihy',
    block:
        'face-framing layers, shorter layered pieces around the face blending into the lengths, soft and flattering',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: false),
  ),
  HairstylePreset(
    id: 'beach-waves',
    label: 'Volné plážové vlny',
    group: kHairGroupWomen,
    section: 'Textura',
    block:
        'beach waves, loose undone tousled waves with natural texture, effortless surf look',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: false),
  ),
  HairstylePreset(
    id: 'soft-curls',
    label: 'Jemné kudrliny',
    group: kHairGroupWomen,
    section: 'Textura',
    block:
        'soft curls, bouncy loose curls with defined ringlets and shine',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: false),
  ),
  HairstylePreset(
    id: 'm-skin-fade',
    label: 'Vysoký skin fade',
    group: kHairGroupMen,
    section: 'Krátké',
    block:
        'high skin fade, sides shaved down to the skin and blended up high, short textured hair on top',
    shape: HairShape(length: HairLength.short, bangs: HairBangs.none, updo: false),
  ),
  HairstylePreset(
    id: 'm-quiff',
    label: 'Quiff',
    group: kHairGroupMen,
    section: 'Střední',
    block:
        'quiff hairstyle, hair on top brushed up and back into a voluminous quiff, shorter tapered sides',
    shape: HairShape(length: HairLength.short, bangs: HairBangs.none, updo: false),
  ),
];

const kHairColours = <HairColourPreset>[
  HairColourPreset(
    id: 'burgundy',
    label: 'Vínová',
    phrase: 'burgundy wine red',
  ),
  HairColourPreset(
    id: 'honey-balayage',
    label: 'Hnědá s medovým balayage',
    phrase: 'brown hair with soft honey blonde balayage highlights toward the ends',
  ),
  HairColourPreset(
    id: 'jet-black',
    label: 'Uhlově černá',
    phrase: 'glossy jet black',
  ),
  HairColourPreset(
    id: 'blue-black',
    label: 'Modročerná',
    phrase: 'blue-black with a cool blue sheen',
  ),
];
