// GENERATED by `lab learn` — do not edit. Regenerate before release.
// snapshot: 2026-09-07T14:02:00Z  gallery: finetune.ol1n.com
// eval: 122 obrázků, 70 hodnocených, práh 10
// sessions: lab-20260901-ballerina, lab-20260905-relief
//
// A `null` below is not a gap — it is a measured refusal, with the reason
// on the line above it. The app then keeps its own constant.

import 'package:ol1n_llm/models/learned.dart';

const kLearned = Learned(
  snapshotAt: '2026-09-07T14:02:00Z',
  ratedImages: 70,
  totalImages: 122,
  minRatings: 10,
  models: {
    'juggernaut-xl': LearnedModel(
      poseAdherence: Rate(0.4, lower: 0.219, upper: 0.613, n: 20),
      sourceIdentity: Rate(0.647, lower: 0.413, upper: 0.827, n: 17),
      likeRate: Rate(0.706, lower: 0.538, upper: 0.832, n: 34),
    ),
    'pony': LearnedModel(
      poseAdherence: Rate(0.903, lower: 0.751, upper: 0.967, n: 31),
      sourceIdentity: Rate(0.615, lower: 0.355, upper: 0.823, n: 13),
      likeRate: Rate(0.824, lower: 0.665, upper: 0.917, n: 34),
    ),
  },
  loraStrength: {
    'face_v1.safetensors': LearnedValue(1.2, reason: 'dolní mez 0.72 > horní 0.54 druhého (0.40 síla), n=22/19'),
    // solo_v1.safetensors: jen jedna síla kdy zkoušená (0.90 síla n=18) — není co porovnat
    // style_v2.safetensors: intervaly se překrývají: 0.90 síla 39–86 % vs 1.10 síla 35–85 %
  },
  defaultModel: {
    // intervaly se překrývají: Pony V6 66–92 % vs Juggernaut XL 54–83 %
    Intent.txt2img: null,
    // intervaly se překrývají: Pony V6 66–92 % vs Juggernaut XL 54–83 %
    Intent.img2img: null,
    Intent.repose: LearnedChoice('pony', reason: 'dolní mez 0.75 > horní 0.61 druhého (Juggernaut XL), n=31/20'),
  },
  styleFlags: {
    'juggernaut-xl': {
      'assyrian': StyleFlag.weak(reason: 'like 1–31 %, n=14'),
    },
    'pony': {
      'assyrian': StyleFlag.weak(reason: 'like 1–30 %, n=15'),
      'ukiyoe': StyleFlag.strong(reason: 'like 77–99 %, n=21'),
    },
  },
);
